short_project_name = "{{short_project_name}}"
project_name       = "{{project_name}}"
subscription_id    = "subscription_id"
tenant_id          = "tenent_id"
client_id          = "client_id"
client_secret      = "client_secret"